
  services:
    web:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        db:
          condition: service_healthy
    db:
      image: postgres
      volumes:
        - /var/lib/postgresql/ucic/data:/var/lib/postgresql/ucic/data
      environment:
        POSTGRES_DB: capstone_db
        POSTGRES_PASSWORD: 12345678
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 1s